# Generated by Django 2.0.13 on 2019-03-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fabricante', models.TextField(max_length=60)),
                ('mililitros', models.IntegerField()),
                ('estabelecimento', models.TextField(max_length=60)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=60)),
                ('endereco', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bebidas')),
                ('id_cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cesta')),
            ],
        ),
    ]
